version: '3.8'

services:
  db:
    build:
      context: .
      args:
        DBPASSWORD: ${DBPASSWORD}
        DBUSER: ${DBUSER}
      dockerfile: db.Dockerfile
    container_name: my_postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_USER: ${DBUSER}
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_web_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code

volumes:
  postgres_data:


