version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code

volumes:
  postgres_data:


